name: Container build

on:
  push:
    branches: [ main ]

jobs:
  pact:
    name: Push pact tests results
    runs-on: ubuntu-latest
    env: 
      PR_NUMBER: ${{ github.event.pull_request.number }}
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_CHECK: true
      OPERATOR_SDK_VERSION: v1.14.0
    steps:
      - name: Test vars
        run: |
          echo "PR_NUMBER: $PR_NUMBER"
          echo "COMMIT_SHA: $COMMIT_SHA"
